local Rioo = loadstring(game:HttpGet("https://raw.githubusercontent.com/RioYang010101/Project-Script-Fish-It/main/RiooUi.lua"))()
local win = Rioo:CreateWindow({Name="Fish It Hub", SubTitle="by Rio"})
local tab = win:CreateTab("Main")
local sec = tab:CreateSection("Auto")
sec:CreateButton("Test Button", function() print("Clicked!") end)